### ISSUE TITLE
Die win-messages sind hardcoded und werden nicht aus der messages.yml geladen

### ISSUE THREAD

**Issue by 1LiterZinalco** [CuukyOfficial/VaroPlugin#14]
Moin!

Server: _CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)_
Das Plugin: _2.2.4_

Ich würde gerne diese Standardnachricht ändern:
![image](https://user-images.githubusercontent.com/42828197/73213509-9e76db00-4150-11ea-990a-1ac4282255b1.png)

In der messages.yml gibt es die Optionen:
```
win:
    player: '%player% hat OsterVaro3 gewonnen! Gratulation!'
    team: Team %team% bestehend aus %winnerPlayers% hat OsterVaro3 gewonnen! Gratulation!
```

Diese werden aber in Minecarft nicht beachtet, da die zu sendene Nachricht hardcoded ist und nicht die Strings aus der Datei verwendet werden:
https://github.com/CuukyOfficial/VaroPlugin/blob/d3d5534e7c935d7c4c78522e2c3db464a83fd90d/Varo%20-%201.7%20-%201.15/src/de/cuuky/varo/game/Game.java#L161

Kannst du da mal ein Auge drauf werfen und das in Zukunft ermöglichen?

**Comment by CuukyOfficial** [comment]
Nachricht hinzugefügt - siehe https://github.com/CuukyOfficial/VaroPlugin/blob/5350badcdcfea9c510ff77f4169c854b80d5b0ca/Varo%20-%201.7%20-%201.15/src/de/cuuky/varo/game/Game.java#L159
