### ISSUE TITLE
"Cuuky FrameWork" 

### ISSUE THREAD

**Issue by LinuxClient** [CuukyOfficial/VaroPlugin#23]
Dear Cuuky,

is there a way to download your "FrameWork"? I want contribute some changes to this plugin. Because this plugin has many issues.

**Comment by CuukyOfficial** [comment]
Hello,
here's the link to the CFW (Cuuky FrameWork):
https://github.com/CuukyOfficial/CFW

**Comment by LinuxClient** [comment]
Hello,

i thank you for that! I would be happy if you would add a compiled version.

**Comment by CuukyOfficial** [comment]
Yeah, I could do that. I'm busy ATM, so it may take a while.
