### ISSUE TITLE
Buildtool

### ISSUE THREAD

**Issue by LinuxClient** [CuukyOfficial/VaroPlugin#25]
Hello,

you should add a build tool like **Gradle** or **Maven**. A public repository server would also be an advantage. This would have the advantage that any developer can add the dependencies without having to download them manually. It would also simplify the compilation process. Lastly: Gradle and Maven supported so-called modulations.

**Comment by CuukyOfficial** [comment]
Hey,

I've already had this idea since release but I don't really know how to use it and since I am very lazy, I never set it up. I would need some more knowledge about Maven and Gradle

**Comment by LinuxClient** [comment]
Hey,

everything's okay! I just saw that you're from Germany? Me too. If you like, I can introduce you to the basics of Maven or Gradle

**Comment by CuukyOfficial** [comment]
Yeah, sure thing. My discord: Cuuky#2783
Btw I'd be glad if we could continue writing in English on GitHub, in private we can talk German then

**Comment by LinuxClient** [comment]
Yes, GitHub is a public platform where English is the preferred language.
