### ISSUE TITLE
[BUG] Varo plugin disable

### ISSUE THREAD

**Issue by ShowMeYourSkil** [CuukyOfficial/VaroPlugin#31]
Hey,

I've a problem with your plugin. When I start the plugin with the bot, it just turns off at startup.

Do you can help me with my problem? 🤔 

![image](https://user-images.githubusercontent.com/39274150/102754936-fec8c980-436d-11eb-852e-d8fd876dc63f.png)

**Comment by ShowMeYourSkil** [comment]
I've fix my problem

**Comment by CuukyOfficial** [comment]
Sorry for not responding, I've not been online on GitHub lately. 
I've you've got more questions feel free to join our Discord Server https://discord.gg/CnDSVVx

There you surely will find help
