### ISSUE TITLE
Disable certain features in worlds

### ISSUE THREAD

**Issue by msengbusch** [CuukyOfficial/VaroPlugin#33]
I've got a question. Is it possible to disable certain features or the complete plugin in different worlds? It would be useful, because there are servers like mine which has got different worlds for different gamemods like survival, ...
Thanks for your response.

**Comment by UeberallGebannt** [comment]
Nope, this isn't possible.
I also wouldn't recommend to setup a server with different worlds for different gamemodes, it's much easier to just setup a bungeecord network so you aren't limited to world compatible plugins.

**Comment by msengbusch** [comment]
Yeah. I though that. I'll set up a bungeecord network to solve the problem. Thanks for your response
