### ISSUE TITLE
Disconnects are not being reset after a session ends

### ISSUE THREAD

**Issue by Almighty-Satan** [CuukyOfficial/VaroPlugin#91]

**Comment by wheatley2056** [comment]
We are currently running a project with the plugin and have the bug that people can still return to the server after their playing time even though they are set to have only one session per day.

```
catchUpSessions: false
ignoreJoinSystemsAsOP: true
joinAfterHours: -1
kickAtServerClose: false
massRecordingTime: 15
onlyJoinBetweenHours: true
onlyJoinBetweenHoursHour1: 15
onlyJoinBetweenHoursMinute1: 0
onlyJoinBetweenHoursHour2: 23
onlyJoinBetweenHoursMinute2: 0
preProduceSessions: 0
sessionsPerDay: -1
```

**Comment by Almighty-Satan** [comment]
> We are currently running a project with the plugin and have the bug that people can still return to the server after their playing time even though they are set to have only one session per day.
> 
> ```
> catchUpSessions: false
> ignoreJoinSystemsAsOP: true
> joinAfterHours: -1
> kickAtServerClose: false
> massRecordingTime: 15
> onlyJoinBetweenHours: true
> onlyJoinBetweenHoursHour1: 15
> onlyJoinBetweenHoursMinute1: 0
> onlyJoinBetweenHoursHour2: 23
> onlyJoinBetweenHoursMinute2: 0
> preProduceSessions: 0
> sessionsPerDay: 1
> ```

The problem you are describing has nothing to do with this issue. Please open a new issue and provide logs from when the problem first occurred as well as your `main.yml` config. Are players actually able to play multiple sessions or are they just joining as spectators?
