### ISSUE TITLE
neue "death" einstellung

### ISSUE THREAD

**Issue by xseesmur** [CuukyOfficial/VaroPlugin#96]
mich würde es freuen wenn man den originellen "death-screen" haben könnte anstatt, dass man in den spectator modus geht für paar sekunden und dan gekickt wird ODER sofort zum menu screen geschickt wird, dass man gestorben ist. Finde das mehr og usw würde mich freuen für og varo events

**Comment by Almighty-Satan** [comment]
Es gibt jetzt eine neue Einstellung `showDeathScreen`, die aber nur beachtet wird, wenn der Spieler nicht aufgrund anderer Einstellungen direkt nach dem Tod vom Server gekickt wird. Eine Beta-Version mit dem Feature gibt es auf unserem Discord.
